---
- name: Install libvirt packages
  pacman:
    name: '{{ packages }}'
    state: latest

- name: "Add user {{ username }} to libvirt group"
  user:
    name: '{{ username }}'
    groups: libvirt
    append: true

- name: Copy libvirt polkit rules
  copy:
    src: 50-libvirt.rules
    dest: /etc/polkit-1/rules.d/50-libvirt.rules

- name: Copy nfs configuration
  copy:
    src: nfs.conf
    dest: /etc/nfs.conf

- name: Copy sudoers configuration for vagrant NFS
  copy:
    src: vagrant-nfs
    dest: /etc/sudoers.d/vagrant-nfs
