---
- name: Install libvirt packages
  pacman:
    name: '{{ libvirt_packages }}'
    state: latest

- name: "Add user {{ username }} to libvirt group"
  user:
    name: '{{ username }}'
    groups: libvirt
    append: true

- name: Copy libvirt polkit rules
  copy:
    src: 50-libvirt.rules
    dest: /etc/polkit-1/rules.d/50-libvirt.rules

- name: Copy nfs configuration
  copy:
    src: nfs.conf
    dest: /etc/nfs.conf

- name: Copy sudoers configuration for vagrant NFS
  copy:
    src: vagrant-nfs
    dest: /etc/sudoers.d/vagrant-nfs

- name: Create /etc/resolv.conf symlink for systemd-resolved
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
