---
- name: Install vim
  pacman:
    name: "{{ packages }}"
    state: latest

- name: Remove unnecessary text editors
  pacman:
    name: "{{ packages_bloat }}"
    state: absent

- name: Install packages (aur)
  aur:
    name: "{{ aur_packages }}"
    skip_installed: true

- name: Install vim LSP (pacman)
  pacman:
    name: "{{ packages_lsp }}"
    state: latest

- name: Install linters (pacman)
  pacman:
    name: "{{ packages_lint }}"
    state: latest

- name: Install linters (npm)
  npm:
    name: "{{ item }}"
    global: true
    state: latest
  become: true
  become_user: "{{ username }}"
  loop: "{{ npm_packages }}"

- name: Create undodir
  file:
    path: "/home/{{ username }}/.vim/undodir"
    state: directory
